---

- import_tasks: ev_user.yml
  when:
    - hana_userid == ''
    - not apply_license

- import_tasks: ev_group.yml
  when:
    - hana_groupid == ''
    - not apply_license

- import_tasks: password_facts.yml
  when: use_master_password == 'y'

- import_tasks: hana_deploy.yml
  when: not apply_license

- import_tasks: license.yml
  when: apply_license