---

- import_tasks: ev_user.yml
  when: hana_userid | length == 0

- import_tasks: ev_group.yml
  when: hana_groupid | length == 0

- name: Use SAPCAR to extract the SAP HANA Bundle SAR file
  command: "{{ sapcar_path }}/{{ sapcar_file_name }} -xvf {{ bundle_path }}/{{ bundle_sar_file_name }} -manifest SIGNATURE.SMF"
  register: extractbundle
  args:
    chdir: "{{ sapcar_path }}"
  changed_when: "'SAPCAR: processing archive' in extractbundle.stdout"

- name: Setting fact for HANA installer path
  set_fact:
    hana_source_path: "{{ sapcar_path }}/SAP_HANA_DATABASE"

- name: create temporary directory to store the processed template
  tempfile:
    state: directory
    suffix: hanaconfig
  register: tmpdir

- name: "Process HANA Configfile Template"
  template:
    src: "{{ role_path }}/templates/configfile.j2"
    dest: "{{ tmpdir.path }}/configfile.cfg"
  register: cftemplate

- name: Install SAP HANA
  command: "./hdblcm --configfile={{ tmpdir.path }}/configfile.cfg -b"
  register: installhana
  args:
    chdir: "{{ hana_source_path }}"
  changed_when: "'SAP HANA Lifecycle Management' in installhana.stdout"
