---

- name: Use SAPCAR to extract the SAP HANA Bundle SAR file
  command: "{{ sapcar_path }}/{{ sapcar_file_name }} -xvf {{ bundle_path }}/{{ bundle_sar_file_name }} -manifest SIGNATURE.SMF"
  register: extractbundle
  args:
    chdir: "{{ sapcar_path }}"
  changed_when: "'SAPCAR: processing archive' in extractbundle.stdout"

- name: Setting fact for HANA installer path
  set_fact:
    hana_source_path: "{{ sapcar_path }}/SAP_HANA_DATABASE"

- name: Install SAP HANA
  command: "./hdblcm --configfile={{ lookup('template', 'configfile.j2') }} -b"
  register: installhana
  args:
    chdir: "{{ hana_source_path }}"
  changed_when: "'SAP HANA Lifecycle Management' in installhana.stdout"
