---

- import_tasks: ev_user.yml
  when: hana_userid == ''

- import_tasks: ev_group.yml
  when: hana_groupid == ''

- import_tasks: password_facts.yml
  when: use_master_password == 'y'

- import_tasks: hana_deploy.yml

- import_tasks: license.yml
  when: apply_license